name: Build

on:
  push:
    branches:
      - main
    tags: 
      - 'v*'


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run scripts/build.ts
      - uses: actions/upload-artifact@v7
        with:
          name: build
          path: dist/
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: build
      - uses: softprops/action-gh-release@v3
        with:
          files: dist/
